"""002_mifhostfe

Revision ID: 4c4894423af9
Revises: 91945ce90f1e
Create Date: 2026-06-19 11:26:46.582768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4894423af9'
down_revision = '91945ce90f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lexa_aux_configuration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aux_mif_host_fe', sa.String(length=3), server_default=sa.text("'J1'"), nullable=False))

    with op.batch_alter_table('lexa_main_configuration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cfg_mif_host_fe', sa.String(length=3), server_default=sa.text("'J1'"), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lexa_main_configuration', schema=None) as batch_op:
        batch_op.drop_column('cfg_mif_host_fe')

    with op.batch_alter_table('lexa_aux_configuration', schema=None) as batch_op:
        batch_op.drop_column('aux_mif_host_fe')

    # ### end Alembic commands ###
