"""003_craisvirgin

Revision ID: 71f9ba2d7877
Revises: 4c4894423af9
Create Date: 2026-07-20 14:03:48.591513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71f9ba2d7877'
down_revision = '4c4894423af9'
branch_labels = None
depends_on = None

FACTORY_PASSWORD_HASH = 'pbkdf2:sha256:150000$vXhx913S$f96ae1cc6bd54e513b192da2be2a9bac1cfd5316f5cab9eaf3a7c91af871c72b'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('via', sa.String(length=15), nullable=True),
    sa.Column('user_name', sa.String(length=23), nullable=True),
    sa.Column('ip', sa.String(length=15), nullable=True),
    sa.Column('event', sa.String(length=23), nullable=True),
    sa.Column('result', sa.String(length=7), nullable=True),
    sa.Column('dt_utc', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_virgin', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    # ### end Alembic commands ###

    # ### Customized commands ###

    local_consts = {
        # --- carrier_configuration
        'cfg_sci1_baud_default': 19200,
        'cfg_sci2_baud_default': 19200,
        'cfg_sci1_mode_default': 'fim_main',
        'cfg_sci2_mode_default': 'kxp_main',
        'cfg_din_echo_0_default': True,
        'cfg_din_echo_1_default': True,
        'cfg_din_echo_2_default': True,
        'cfg_din_echo_3_default': True,
        'cfg_din_echo_4_default': True,
        'cfg_ttl0_mode_default': 'aba_tk2',
        'cfg_ttl1_mode_default': 'aba_tk2',
        'cfg_fim0_operating_baud_default': 38400,
        'cfg_fim1_operating_baud_default': 38400,
        'cfg_sfm0_operating_baud_default': 115200,
        'cfg_sfm1_operating_baud_default': 115200,
        # --- lexa_aux/main_configuration
        'din_echo_0_default': True,
        'din_echo_1_default': True,
        'mif_host_fe_default': 'J1',
        'mif_mode_default': 'atqa_uid',
        'mif_block_number_default': 0,
        'mif_login_mode_default': 'auto',
        'mif_key_ab_default': 'keya_isoauth',
        'mif_key_number_default': 0,
        'mif_read_ok_led_mode_default': 'on',
        'mif_read_ok_led_color_default': 'green',
        'mif_read_ok_led_time_on_10ms_default': 50,
        'mif_read_fail_led_mode_default': 'on',
        'mif_read_fail_led_color_default': 'red',
        'mif_read_fail_led_time_on_10ms_default': 100,
        'mif_read_ok_bzz_mode_default': 'on',
        'mif_read_ok_bzz_time_on_10ms_default': 22,
        'mif_read_fail_bzz_mode_default': 'on',
        'mif_read_fail_bzz_time_on_10ms_default': 50,
        'mif_inter_instruction_tmo_10ms_default': 100,
        'mif_field_off_duration_10ms_default': 100,
        'mif_keep_field_on_time_ds_default': 10,
        'mif_rx_gain_default': '40db',
        'mif_msector_sel_default': '1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0',
        'mif_msector_keyab_default': 'a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a',
        # --- nano_configuration
        'terminal_description_default': 'Kapri_Online',
        'rtc_local_timezone_default': 'CET',
        'network_ip_address_default': '192.168.123.123',
        'network_bits_mask_default': 24,
        'network_ip_router_default': '192.168.123.1',
        'network_dhcp_mode_default': 'DHCP',
        'wlan_enabled_default': False,
        'wlan_ssid_default': '0123456789',
        'wlan_password_default': '0123456789',
        'interface_ins_pwd_default': '',
        'ktp_interface_default': True,
        'jso_interface_default': True,
        'http_interface_default': True,
        'cloud_interface_default': False,
        'ktp_server_client_mode_default': 'Client',
        'ktp_remote_server_ip_1_default': '',
        'ktp_remote_server_ip_2_default': '',
        'ktp_remote_server_port_1_default': 65431,
        'ktp_remote_server_port_2_default': 65431,
        'ktp_udp_detect_default': True,
        'ktp_udp_port_default': 6050,
        'ktp_network_id_default': 'test_network_kapri',
        'ktp_aes256_default': '0123456789012345678901234567890123456789012345678901234567890123',
        'jso_server_client_mode_default': 'Server',
        'jso_remote_server_ip_1_default': '',
        'jso_remote_server_port_1_default': 65441,
        'jso_remote_server_ip_2_default': '',
        'jso_remote_server_port_2_default': 65441,
        'http_socketio_server_host_default': '',
        'http_socketio_server_port_default': 33001,
        'cloud_remote_server_url_default': '',
        'cloud_remote_server_token_default': '',
        'cloud_allowed_events_default': 'on_cloud_keep_alive,on_cpu_boot,on_semi_offline_mode_leave,on_usrtimer_elapsed,on_inout_digital_input_get_echo,on_mifare_track,on_ttl_track,on_fim_finger,on_keyboard_echo,on_uart_receive',
        'cloud_keep_alive_timeout_default': 15,
        'cloud_busy_relay_default': -1,
        'semi_offline_mode_enabled_default': False,
        'semi_offline_keep_alive_timeout_default': 300,
        'semi_offline_on_semi_offline_mode_enter_batch_default': '',
        'semi_offline_on_usrtimer_elapsed_batch_default': '',
        'semi_offline_on_mifare_track_batch_default': '',
        'semi_offline_on_ttl_track_batch_default': '',
        'semi_offline_on_fim_finger_batch_default': '',
        'semi_offline_on_sfm_finger_batch_default': '',
        'semi_offline_on_keyboard_echo_batch_default': '',
        'semi_offline_on_uart_receive_batch_default': '',
        'scankey_encoding_default': 'R4x1',
        'kybmgr_enabled_default': False,
        'kybmgr_cfg_1_default': '',
        'screen_html_boot_default': '',
    }

    # --- tables (totes les columnes existents a la BD en aquest punt: 000 + 001 + 002) ---

    table_carrier_configuration = sa.table(
        'carrier_configuration',
        sa.column('id', sa.Integer),
        sa.column('cfg_sci1_baud', sa.Integer),
        sa.column('cfg_sci2_baud', sa.Integer),
        sa.column('cfg_sci1_mode', sa.String),
        sa.column('cfg_sci2_mode', sa.String),
        sa.column('cfg_din_echo_0', sa.Boolean),
        sa.column('cfg_din_echo_1', sa.Boolean),
        sa.column('cfg_din_echo_2', sa.Boolean),
        sa.column('cfg_din_echo_3', sa.Boolean),
        sa.column('cfg_din_echo_4', sa.Boolean),
        sa.column('cfg_ttl0_mode', sa.String),
        sa.column('cfg_ttl1_mode', sa.String),
        sa.column('cfg_fim0_operating_baud', sa.Integer),
        sa.column('cfg_fim1_operating_baud', sa.Integer),
        sa.column('cfg_sfm0_operating_baud', sa.Integer),
        sa.column('cfg_sfm1_operating_baud', sa.Integer),
    )

    table_lexa_aux_configuration = sa.table(
        'lexa_aux_configuration',
        sa.column('id', sa.Integer),
        sa.column('aux_din_echo_0', sa.Boolean),
        sa.column('aux_din_echo_1', sa.Boolean),
        sa.column('aux_mif_host_fe', sa.String),
        sa.column('aux_mif_mode', sa.String),
        sa.column('aux_mif_block_number', sa.Integer),
        sa.column('aux_mif_login_mode', sa.String),
        sa.column('aux_mif_key_ab', sa.String),
        sa.column('aux_mif_key_number', sa.Integer),
        sa.column('aux_mif_read_ok_led_mode', sa.String),
        sa.column('aux_mif_read_ok_led_color', sa.String),
        sa.column('aux_mif_read_ok_led_time_on_10ms', sa.Integer),
        sa.column('aux_mif_read_fail_led_mode', sa.String),
        sa.column('aux_mif_read_fail_led_color', sa.String),
        sa.column('aux_mif_read_fail_led_time_on_10ms', sa.Integer),
        sa.column('aux_mif_read_ok_bzz_mode', sa.String),
        sa.column('aux_mif_read_ok_bzz_time_on_10ms', sa.Integer),
        sa.column('aux_mif_read_fail_bzz_mode', sa.String),
        sa.column('aux_mif_read_fail_bzz_time_on_10ms', sa.Integer),
        sa.column('aux_mif_inter_instruction_tmo_10ms', sa.Integer),
        sa.column('aux_mif_field_off_duration_10ms', sa.Integer),
        sa.column('aux_mif_keep_field_on_time_ds', sa.Integer),
        sa.column('aux_mif_rx_gain', sa.String),
        sa.column('aux_mif_msector_sel', sa.String),
        sa.column('aux_mif_msector_keyab', sa.String),
    )

    table_lexa_main_configuration = sa.table(
        'lexa_main_configuration',
        sa.column('id', sa.Integer),
        sa.column('exp_din_echo_0', sa.Boolean),
        sa.column('exp_din_echo_1', sa.Boolean),
        sa.column('cfg_mif_host_fe', sa.String),
        sa.column('cfg_mif_mode', sa.String),
        sa.column('cfg_mif_block_number', sa.Integer),
        sa.column('cfg_mif_login_mode', sa.String),
        sa.column('cfg_mif_key_ab', sa.String),
        sa.column('cfg_mif_key_number', sa.Integer),
        sa.column('exp_mif_read_ok_led_mode', sa.String),
        sa.column('exp_mif_read_ok_led_color', sa.String),
        sa.column('exp_mif_read_ok_led_time_on_10ms', sa.Integer),
        sa.column('exp_mif_read_fail_led_mode', sa.String),
        sa.column('exp_mif_read_fail_led_color', sa.String),
        sa.column('exp_mif_read_fail_led_time_on_10ms', sa.Integer),
        sa.column('exp_mif_read_ok_bzz_mode', sa.String),
        sa.column('exp_mif_read_ok_bzz_time_on_10ms', sa.Integer),
        sa.column('exp_mif_read_fail_bzz_mode', sa.String),
        sa.column('exp_mif_read_fail_bzz_time_on_10ms', sa.Integer),
        sa.column('cfg_mif_inter_instruction_tmo_10ms', sa.Integer),
        sa.column('cfg_mif_field_off_duration_10ms', sa.Integer),
        sa.column('cfg_mif_keep_field_on_time_ds', sa.Integer),
        sa.column('cfg_mif_rx_gain', sa.String),
        sa.column('cfg_mif_msector_sel', sa.String),
        sa.column('cfg_mif_msector_keyab', sa.String),
    )

    table_nano_configuration = sa.table(
        'nano_configuration',
        sa.column('id', sa.Integer),
        sa.column('terminal_description', sa.String),
        sa.column('rtc_local_timezone', sa.String),
        sa.column('network_ip_address', sa.String),
        sa.column('network_bits_mask', sa.Integer),
        sa.column('network_ip_router', sa.String),
        sa.column('network_dhcp_mode', sa.String),
        sa.column('wlan_enabled', sa.Boolean),
        sa.column('wlan_ssid', sa.String),
        sa.column('wlan_password', sa.String),
        sa.column('interface_ins_pwd', sa.String),
        sa.column('ktp_interface', sa.Boolean),
        sa.column('jso_interface', sa.Boolean),
        sa.column('http_interface', sa.Boolean),
        sa.column('cloud_interface', sa.Boolean),
        sa.column('ktp_server_client_mode', sa.String),
        sa.column('ktp_remote_server_ip_1', sa.String),
        sa.column('ktp_remote_server_ip_2', sa.String),
        sa.column('ktp_remote_server_port_1', sa.Integer),
        sa.column('ktp_remote_server_port_2', sa.Integer),
        sa.column('ktp_udp_detect', sa.Boolean),
        sa.column('ktp_udp_port', sa.Integer),
        sa.column('ktp_network_id', sa.String),
        sa.column('ktp_aes256', sa.String),
        sa.column('jso_server_client_mode', sa.String),
        sa.column('jso_remote_server_ip_1', sa.String),
        sa.column('jso_remote_server_port_1', sa.Integer),
        sa.column('jso_remote_server_ip_2', sa.String),
        sa.column('jso_remote_server_port_2', sa.Integer),
        sa.column('http_socketio_server_host', sa.String),
        sa.column('http_socketio_server_port', sa.Integer),
        sa.column('cloud_remote_server_url', sa.String),
        sa.column('cloud_remote_server_token', sa.String),
        sa.column('cloud_allowed_events', sa.String),
        sa.column('cloud_keep_alive_timeout', sa.Integer),
        sa.column('cloud_busy_relay', sa.Integer),
        sa.column('semi_offline_mode_enabled', sa.Boolean),
        sa.column('semi_offline_keep_alive_timeout', sa.Integer),
        sa.column('semi_offline_on_semi_offline_mode_enter_batch', sa.String),
        sa.column('semi_offline_on_usrtimer_elapsed_batch', sa.String),
        sa.column('semi_offline_on_mifare_track_batch', sa.String),
        sa.column('semi_offline_on_ttl_track_batch', sa.String),
        sa.column('semi_offline_on_fim_finger_batch', sa.String),
        sa.column('semi_offline_on_sfm_finger_batch', sa.String),
        sa.column('semi_offline_on_keyboard_echo_batch', sa.String),
        sa.column('semi_offline_on_uart_receive_batch', sa.String),
        sa.column('scankey_encoding', sa.String),
        sa.column('kybmgr_enabled', sa.Boolean),
        sa.column('kybmgr_cfg_1', sa.String),
        sa.column('screen_html_boot', sa.String),
    )

    # --- deduïm is_virgin a partir del valor actual de user_password_hash ---
    op.execute(
        f"""
        UPDATE users
           SET is_virgin = CASE
               WHEN user_password_hash = '{FACTORY_PASSWORD_HASH}' THEN 1
               ELSE 0
           END
        """
    )

    # --- inserim registre de configuració de fàbrica (id=4) ---
    op.bulk_insert(
        table_carrier_configuration,
        [{
            'id': 4,
            'cfg_sci1_baud': local_consts.get('cfg_sci1_baud_default'),
            'cfg_sci2_baud': local_consts.get('cfg_sci2_baud_default'),
            'cfg_sci1_mode': local_consts.get('cfg_sci1_mode_default'),
            'cfg_sci2_mode': local_consts.get('cfg_sci2_mode_default'),
            'cfg_din_echo_0': local_consts.get('cfg_din_echo_0_default'),
            'cfg_din_echo_1': local_consts.get('cfg_din_echo_1_default'),
            'cfg_din_echo_2': local_consts.get('cfg_din_echo_2_default'),
            'cfg_din_echo_3': local_consts.get('cfg_din_echo_3_default'),
            'cfg_din_echo_4': local_consts.get('cfg_din_echo_4_default'),
            'cfg_ttl0_mode': local_consts.get('cfg_ttl0_mode_default'),
            'cfg_ttl1_mode': local_consts.get('cfg_ttl1_mode_default'),
            'cfg_fim0_operating_baud': local_consts.get('cfg_fim0_operating_baud_default'),
            'cfg_fim1_operating_baud': local_consts.get('cfg_fim1_operating_baud_default'),
            'cfg_sfm0_operating_baud': local_consts.get('cfg_sfm0_operating_baud_default'),
            'cfg_sfm1_operating_baud': local_consts.get('cfg_sfm1_operating_baud_default'),
        }],
    )

    op.bulk_insert(
        table_lexa_aux_configuration,
        [{
            'id': 4,
            'aux_din_echo_0': local_consts.get('din_echo_0_default'),
            'aux_din_echo_1': local_consts.get('din_echo_1_default'),
            'aux_mif_host_fe': local_consts.get('mif_host_fe_default'),
            'aux_mif_mode': local_consts.get('mif_mode_default'),
            'aux_mif_block_number': local_consts.get('mif_block_number_default'),
            'aux_mif_login_mode': local_consts.get('mif_login_mode_default'),
            'aux_mif_key_ab': local_consts.get('mif_key_ab_default'),
            'aux_mif_key_number': local_consts.get('mif_key_number_default'),
            'aux_mif_read_ok_led_mode': local_consts.get('mif_read_ok_led_mode_default'),
            'aux_mif_read_ok_led_color': local_consts.get('mif_read_ok_led_color_default'),
            'aux_mif_read_ok_led_time_on_10ms': local_consts.get('mif_read_ok_led_time_on_10ms_default'),
            'aux_mif_read_fail_led_mode': local_consts.get('mif_read_fail_led_mode_default'),
            'aux_mif_read_fail_led_color': local_consts.get('mif_read_fail_led_color_default'),
            'aux_mif_read_fail_led_time_on_10ms': local_consts.get('mif_read_fail_led_time_on_10ms_default'),
            'aux_mif_read_ok_bzz_mode': local_consts.get('mif_read_ok_bzz_mode_default'),
            'aux_mif_read_ok_bzz_time_on_10ms': local_consts.get('mif_read_ok_bzz_time_on_10ms_default'),
            'aux_mif_read_fail_bzz_mode': local_consts.get('mif_read_fail_bzz_mode_default'),
            'aux_mif_read_fail_bzz_time_on_10ms': local_consts.get('mif_read_fail_bzz_time_on_10ms_default'),
            'aux_mif_inter_instruction_tmo_10ms': local_consts.get('mif_inter_instruction_tmo_10ms_default'),
            'aux_mif_field_off_duration_10ms': local_consts.get('mif_field_off_duration_10ms_default'),
            'aux_mif_keep_field_on_time_ds': local_consts.get('mif_keep_field_on_time_ds_default'),
            'aux_mif_rx_gain': local_consts.get('mif_rx_gain_default'),
            'aux_mif_msector_sel': local_consts.get('mif_msector_sel_default'),
            'aux_mif_msector_keyab': local_consts.get('mif_msector_keyab_default'),
        }],
    )

    op.bulk_insert(
        table_lexa_main_configuration,
        [{
            'id': 4,
            'exp_din_echo_0': local_consts.get('din_echo_0_default'),
            'exp_din_echo_1': local_consts.get('din_echo_1_default'),
            'cfg_mif_host_fe': local_consts.get('mif_host_fe_default'),
            'cfg_mif_mode': local_consts.get('mif_mode_default'),
            'cfg_mif_block_number': local_consts.get('mif_block_number_default'),
            'cfg_mif_login_mode': local_consts.get('mif_login_mode_default'),
            'cfg_mif_key_ab': local_consts.get('mif_key_ab_default'),
            'cfg_mif_key_number': local_consts.get('mif_key_number_default'),
            'exp_mif_read_ok_led_mode': local_consts.get('mif_read_ok_led_mode_default'),
            'exp_mif_read_ok_led_color': local_consts.get('mif_read_ok_led_color_default'),
            'exp_mif_read_ok_led_time_on_10ms': local_consts.get('mif_read_ok_led_time_on_10ms_default'),
            'exp_mif_read_fail_led_mode': local_consts.get('mif_read_fail_led_mode_default'),
            'exp_mif_read_fail_led_color': local_consts.get('mif_read_fail_led_color_default'),
            'exp_mif_read_fail_led_time_on_10ms': local_consts.get('mif_read_fail_led_time_on_10ms_default'),
            'exp_mif_read_ok_bzz_mode': local_consts.get('mif_read_ok_bzz_mode_default'),
            'exp_mif_read_ok_bzz_time_on_10ms': local_consts.get('mif_read_ok_bzz_time_on_10ms_default'),
            'exp_mif_read_fail_bzz_mode': local_consts.get('mif_read_fail_bzz_mode_default'),
            'exp_mif_read_fail_bzz_time_on_10ms': local_consts.get('mif_read_fail_bzz_time_on_10ms_default'),
            'cfg_mif_inter_instruction_tmo_10ms': local_consts.get('mif_inter_instruction_tmo_10ms_default'),
            'cfg_mif_field_off_duration_10ms': local_consts.get('mif_field_off_duration_10ms_default'),
            'cfg_mif_keep_field_on_time_ds': local_consts.get('mif_keep_field_on_time_ds_default'),
            'cfg_mif_rx_gain': local_consts.get('mif_rx_gain_default'),
            'cfg_mif_msector_sel': local_consts.get('mif_msector_sel_default'),
            'cfg_mif_msector_keyab': local_consts.get('mif_msector_keyab_default'),
        }],
    )

    op.bulk_insert(
        table_nano_configuration,
        [{
            'id': 4,
            'terminal_description': local_consts.get('terminal_description_default'),
            'rtc_local_timezone': local_consts.get('rtc_local_timezone_default'),
            'network_ip_address': local_consts.get('network_ip_address_default'),
            'network_bits_mask': local_consts.get('network_bits_mask_default'),
            'network_ip_router': local_consts.get('network_ip_router_default'),
            'network_dhcp_mode': local_consts.get('network_dhcp_mode_default'),
            'wlan_enabled': local_consts.get('wlan_enabled_default'),
            'wlan_ssid': local_consts.get('wlan_ssid_default'),
            'wlan_password': local_consts.get('wlan_password_default'),
            'interface_ins_pwd': local_consts.get('interface_ins_pwd_default'),
            'ktp_interface': local_consts.get('ktp_interface_default'),
            'jso_interface': local_consts.get('jso_interface_default'),
            'http_interface': local_consts.get('http_interface_default'),
            'cloud_interface': local_consts.get('cloud_interface_default'),
            'ktp_server_client_mode': local_consts.get('ktp_server_client_mode_default'),
            'ktp_remote_server_ip_1': local_consts.get('ktp_remote_server_ip_1_default'),
            'ktp_remote_server_ip_2': local_consts.get('ktp_remote_server_ip_2_default'),
            'ktp_remote_server_port_1': local_consts.get('ktp_remote_server_port_1_default'),
            'ktp_remote_server_port_2': local_consts.get('ktp_remote_server_port_2_default'),
            'ktp_udp_detect': local_consts.get('ktp_udp_detect_default'),
            'ktp_udp_port': local_consts.get('ktp_udp_port_default'),
            'ktp_network_id': local_consts.get('ktp_network_id_default'),
            'ktp_aes256': local_consts.get('ktp_aes256_default'),
            'jso_server_client_mode': local_consts.get('jso_server_client_mode_default'),
            'jso_remote_server_ip_1': local_consts.get('jso_remote_server_ip_1_default'),
            'jso_remote_server_port_1': local_consts.get('jso_remote_server_port_1_default'),
            'jso_remote_server_ip_2': local_consts.get('jso_remote_server_ip_2_default'),
            'jso_remote_server_port_2': local_consts.get('jso_remote_server_port_2_default'),
            'http_socketio_server_host': local_consts.get('http_socketio_server_host_default'),
            'http_socketio_server_port': local_consts.get('http_socketio_server_port_default'),
            'cloud_remote_server_url': local_consts.get('cloud_remote_server_url_default'),
            'cloud_remote_server_token': local_consts.get('cloud_remote_server_token_default'),
            'cloud_allowed_events': local_consts.get('cloud_allowed_events_default'),
            'cloud_keep_alive_timeout': local_consts.get('cloud_keep_alive_timeout_default'),
            'cloud_busy_relay': local_consts.get('cloud_busy_relay_default'),
            'semi_offline_mode_enabled': local_consts.get('semi_offline_mode_enabled_default'),
            'semi_offline_keep_alive_timeout': local_consts.get('semi_offline_keep_alive_timeout_default'),
            'semi_offline_on_semi_offline_mode_enter_batch': local_consts.get('semi_offline_on_semi_offline_mode_enter_batch_default'),
            'semi_offline_on_usrtimer_elapsed_batch': local_consts.get('semi_offline_on_usrtimer_elapsed_batch_default'),
            'semi_offline_on_mifare_track_batch': local_consts.get('semi_offline_on_mifare_track_batch_default'),
            'semi_offline_on_ttl_track_batch': local_consts.get('semi_offline_on_ttl_track_batch_default'),
            'semi_offline_on_fim_finger_batch': local_consts.get('semi_offline_on_fim_finger_batch_default'),
            'semi_offline_on_sfm_finger_batch': local_consts.get('semi_offline_on_sfm_finger_batch_default'),
            'semi_offline_on_keyboard_echo_batch': local_consts.get('semi_offline_on_keyboard_echo_batch_default'),
            'semi_offline_on_uart_receive_batch': local_consts.get('semi_offline_on_uart_receive_batch_default'),
            'scankey_encoding': local_consts.get('scankey_encoding_default'),
            'kybmgr_enabled': local_consts.get('kybmgr_enabled_default'),
            'kybmgr_cfg_1': local_consts.get('kybmgr_cfg_1_default'),
            'screen_html_boot': local_consts.get('screen_html_boot_default'),
        }],
    )

    # ### end Customized commands ###


def downgrade():
    # ### Customized commands (revert dels inserts) ###
    op.execute("DELETE FROM nano_configuration WHERE id = 4")
    op.execute("DELETE FROM lexa_main_configuration WHERE id = 4")
    op.execute("DELETE FROM lexa_aux_configuration WHERE id = 4")
    op.execute("DELETE FROM carrier_configuration WHERE id = 4")
    # ### end Customized commands ###

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_virgin')

    op.drop_table('audit_entry')
    # ### end Alembic commands ###
