"""001_busyrelay

Revision ID: 91945ce90f1e
Revises: 0547bbdfc17e
Create Date: 2025-12-11 09:08:32.260996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91945ce90f1e'
down_revision = '0547bbdfc17e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nano_configuration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cloud_busy_relay', sa.Integer(), server_default=sa.text('-1'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nano_configuration', schema=None) as batch_op:
        batch_op.drop_column('cloud_busy_relay')

    # ### end Alembic commands ###
