title = "configuration for debug on pc"

[debug]
debug_level = "DEBUG"

[api]
api_host = "0.0.0.0"
api_port = 12443

[url]
url_kapriassistapi = "http://10.0.0.150:45775"
url_kxphostproapi = "http://10.0.0.150:9443"
url_ktpterminalapi = "http://10.0.0.150:11443"
url_jsoterminalapi = "http://10.0.0.150:9444"
url_httpterminalapi = "http://10.0.0.150:9445"
url_knpupdaterrxapi = "http://10.0.0.150:9442"

[socketio]
socketio_server_host = "10.0.0.150"
socketio_server_port = 33000

[database]
database_uri = "sqlite:///D:\\Apli\\Kapri2_GIT\\Kapri2API\\instance\\kapridb.sqlite"

[routes]
routes_imgrepo_dir = 'imgrepo/'